name: AWS S3 MAIN SERVER DEPLOY

on:
  push:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      GCP_OAUTH_CLIENT_ID: ${{ vars.GCP_OAUTH_CLIENT_ID }}
      SERVICE_URL: ${{ vars.SERVICE_URL }}
      API_URL: ${{ vars.API_URL }}
    steps:
      - name: Print environment variables
        run: |
          echo GCP_OAUTH_CLIENT_ID: ${{ vars.GCP_OAUTH_CLIENT_ID }}
          echo SERVICE_URL: ${{ vars.SERVICE_URL }}
          echo API_URL: ${{ vars.API_URL }}
          echo AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          echo AWS_SECRET_ACCESS_KEY: ${{ vars.AWS_SECRET_ACCESS_KEY }}
          echo AWS_REGION: ${{ vars.AWS_REGION }}
          echo AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
          echo CLOUDFRONT_DISTRIBUTION_ID: ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}
          
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: AWS CLI set
        run: |
          aws configure set aws_access_key_id ${{ vars.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ vars.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ vars.AWS_REGION }}

      - name: S3 sync
        run: |
          aws s3 sync --include "*" --acl public-read --follow-symlinks --delete ./dist s3://${{ vars.AWS_S3_BUCKET }}
        shell: bash

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
        shell: bash
