name: AWS S3 MAIN SERVER DEPLOY

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      BACKEND_URL: ${{ vars.BACKEND_URL }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
          bucket: ${{ secrets.AWS_S3_BUCKET }}
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          source_dir: 'dist/'

      - name: Invalidate CloudFront cache
        run: |
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws configure set default.region ${{ vars.AWS_REGION }}
            aws cloudfront create-invalidation --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
        shell: bash
