name: AWS S3 MAIN SERVER DEPLOY

on:
  push:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest
    
    env:
      BACKEND_URL: ${{ secrets.BACKEND_URL }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        
      - name : AWS CLI set
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}

      - name: S3 sync
        run: |
          aws s3 sync --include "*" --acl public-read --follow-symlinks --delete ./dist s3://${{ secrets.AWS_S3_BUCKET }} --profile bird2
        shell: bash

      - name: Invalidate CloudFront cache
        run: |
            aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
        shell: bash
